/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminWelcomeActivity.java
 *
 * Created on Oct 6, 2015, 5:34:06 PM
 */
package com.ims.view.welcome;

import com.ims.infra.Activity;
import com.ims.infra.Intent;
import com.ims.view.ActivityId;
import com.ims.view.addproduct.ProdType;
import com.ims.view.login.LoginSession;
import com.ims.view.login.RoleConstants;
import java.awt.Container;

/**
 *
 * @author ahbaba
 */
public class AdminWelcomeActivity extends Activity {

    /** Creates new form AdminWelcomeActivity */
    public AdminWelcomeActivity() {
        super.onCreate();
        initComponents();
        customizeUIForRole();
    }

    @Override
    protected void onCreate() {
        super.onCreate();
        Container pane = (Container) getIntent().getExtra("com.ims.view.CONTENTPANE");
        pane.add(this);
        this.setVisible(true);
        this.revalidate();
    }

    @Override
    protected void onStart() {
        super.onStart();
    }

    @Override
    protected void onStop() {
        super.onStop();

    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        ((Container) getIntent().getExtra("com.ims.view.CONTENTPANE")).remove(this);
        setVisible(false);
        ((Container) getIntent().getExtra("com.ims.view.CONTENTPANE")).repaint();
    }

    private void customizeUIForRole() {
        int role = LoginSession.getLoginSession().getuRole();
        if (role == RoleConstants.USER_FOOD) {
            generateReportBtn3.setVisible(false);
            addFoodBtn.setVisible(false);
            addToyBtn.setVisible(false);
        }
        if (role == RoleConstants.USER_TOY) {
            generateReportBtn3.setVisible(false);
            addFoodBtn.setVisible(false);
            addToyBtn.setVisible(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generateReportBtn2 = new javax.swing.JButton();
        addUserBtn1 = new javax.swing.JButton();
        addToyBtn = new javax.swing.JButton();
        addFoodBtn = new javax.swing.JButton();
        changePriceButton3 = new javax.swing.JButton();
        addProductBtn3 = new javax.swing.JButton();
        generateReportBtn3 = new javax.swing.JButton();
        generateReportBtn4 = new javax.swing.JButton();

        generateReportBtn2.setBackground(new java.awt.Color(204, 204, 255));
        generateReportBtn2.setFont(new java.awt.Font("Tahoma", 1, 24));
        generateReportBtn2.setText("Billing");
        generateReportBtn2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        generateReportBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportBtn2ActionPerformed(evt);
            }
        });

        addUserBtn1.setBackground(new java.awt.Color(204, 204, 255));
        addUserBtn1.setFont(new java.awt.Font("Tahoma", 1, 24));
        addUserBtn1.setText("Play Area");
        addUserBtn1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addUserBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserBtn1ActionPerformed(evt);
            }
        });

        addToyBtn.setBackground(new java.awt.Color(204, 204, 255));
        addToyBtn.setFont(new java.awt.Font("Tahoma", 1, 24));
        addToyBtn.setText("Add Toys");
        addToyBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addToyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToyBtnActionPerformed(evt);
            }
        });

        addFoodBtn.setBackground(new java.awt.Color(204, 204, 255));
        addFoodBtn.setFont(new java.awt.Font("Tahoma", 1, 24));
        addFoodBtn.setText("Add Food");
        addFoodBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addFoodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFoodBtnActionPerformed(evt);
            }
        });

        changePriceButton3.setBackground(new java.awt.Color(204, 204, 255));
        changePriceButton3.setFont(new java.awt.Font("Tahoma", 1, 24));
        changePriceButton3.setText("Configure Play Area");
        changePriceButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        changePriceButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePriceButton3ActionPerformed(evt);
            }
        });

        addProductBtn3.setBackground(new java.awt.Color(204, 204, 255));
        addProductBtn3.setFont(new java.awt.Font("Tahoma", 1, 24));
        addProductBtn3.setText("Logout");
        addProductBtn3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addProductBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductBtn3ActionPerformed(evt);
            }
        });

        generateReportBtn3.setBackground(new java.awt.Color(204, 204, 255));
        generateReportBtn3.setFont(new java.awt.Font("Tahoma", 1, 24));
        generateReportBtn3.setText("Book Party Hall");
        generateReportBtn3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        generateReportBtn4.setBackground(new java.awt.Color(204, 204, 255));
        generateReportBtn4.setFont(new java.awt.Font("Tahoma", 1, 24));
        generateReportBtn4.setText("Generate Report");
        generateReportBtn4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(generateReportBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(generateReportBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(addFoodBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addToyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addProductBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(addUserBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(generateReportBtn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changePriceButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(365, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addFoodBtn, addProductBtn3, addToyBtn, addUserBtn1, changePriceButton3, generateReportBtn2, generateReportBtn3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFoodBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addToyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUserBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changePriceButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addProductBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generateReportBtn4, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(generateReportBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                        .addComponent(generateReportBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)))
                .addContainerGap(564, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addFoodBtn, addToyBtn, addUserBtn1, changePriceButton3, generateReportBtn2, generateReportBtn3});

    }// </editor-fold>//GEN-END:initComponents

    private void generateReportBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportBtn2ActionPerformed
        // TODO add your handling code here:
        Intent intent = getIntent().getIntent(ActivityId.BILLING_TABLE_ACTIVITY);
//          intent.putExtra("com.ims.view.CONTENTPANE", (Container) getIntent().getExtra("com.ims.view.CONTENTPANE"));;
        startActivity(intent);
}//GEN-LAST:event_generateReportBtn2ActionPerformed

    private void addUserBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserBtn1ActionPerformed
        // TODO add your handling code here:
          Intent intent = getIntent().getIntent(ActivityId.PLAY_ZONE_ACTIVITY);
//          intent.putExtra("com.ims.view.CONTENTPANE", (Container) getIntent().getExtra("com.ims.view.CONTENTPANE"));;
        startActivity(intent);
}//GEN-LAST:event_addUserBtn1ActionPerformed

    private void addToyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToyBtnActionPerformed
        Intent intent = new Intent(ActivityId.ADD_PRODUCT_ACTIVITY);
        intent.putExtra("com.ims.view.CONTENTPANE", (Container) getIntent().getExtra("com.ims.view.CONTENTPANE"));
        intent.putExtra("com.ims.view.welcome.ITEM", ProdType.TOY);
        startActivity(intent);

}//GEN-LAST:event_addToyBtnActionPerformed

    private void addFoodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFoodBtnActionPerformed
        Intent intent = new Intent(ActivityId.ADD_PRODUCT_ACTIVITY);
        intent.putExtra("com.ims.view.CONTENTPANE", (Container) getIntent().getExtra("com.ims.view.CONTENTPANE"));
        intent.putExtra("com.ims.view.welcome.ITEM", ProdType.FOOD);
        startActivity(intent);
}//GEN-LAST:event_addFoodBtnActionPerformed

    private void changePriceButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePriceButton3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_changePriceButton3ActionPerformed

    private void addProductBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductBtn3ActionPerformed
        // TODO add your handling code here:
        Intent intent = getIntent().getIntent(ActivityId.LOGIN_ACTIVITY);
        LoginSession.getLoginSession().destroyLoginSession();
        startActivity(intent);

}//GEN-LAST:event_addProductBtn3ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFoodBtn;
    private javax.swing.JButton addProductBtn3;
    private javax.swing.JButton addToyBtn;
    private javax.swing.JButton addUserBtn1;
    private javax.swing.JButton changePriceButton3;
    private javax.swing.JButton generateReportBtn2;
    private javax.swing.JButton generateReportBtn3;
    private javax.swing.JButton generateReportBtn4;
    // End of variables declaration//GEN-END:variables
}
