/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BillingActivity.java
 *
 * Created on Oct 7, 2015, 10:19:38 PM
 */

package com.ims.view.billingx;

import com.ims.controller.TransactionManager;
import com.ims.infra.Activity;
import com.ims.infra.Intent;
import com.ims.model.bean.ItemDAO;
import com.ims.model.bean.TransactionModel;
import com.ims.util.Util;
import com.ims.view.ActivityId;
import java.awt.Container;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
//import kidsomania.controller.TransactionManager;
//import kidsomania.model.PurchasedCart;
//import kidsomania.model.TransactionModel;
//import kidsomania.view.WelcomePage;

/**
 *
 * @author ahbaba
 */
public class BillingActivity extends Activity {

    private DefaultTableModel model;
    private PurchasedCart pCart;

    /** Creates new form BillingActivity */
    public BillingActivity() {
      
    }

    @Override
    protected void onCreate() {
       super.onCreate();
       initComponents();
       Container pane = (Container)getIntent().getExtra("com.ims.view.CONTENTPANE");
       pane.add(this);
       this.setVisible(true);
       this.revalidate();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
         ((Container) getIntent().getExtra("com.ims.view.CONTENTPANE")).remove(this);
        setVisible(false);
        ((Container) getIntent().getExtra("com.ims.view.CONTENTPANE")).repaint();
        model = null;
        pCart = null;
    }

    @Override
    protected void onStart() {
        super.onStart();
    }

    @Override
    protected void onStop() {
        super.onStop();
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        billTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        userIDLabel = new javax.swing.JLabel();
        confirmBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        customerIDText = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        vatCombobox = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        totalLable = new javax.swing.JLabel();
        totalLable1 = new javax.swing.JLabel();
        totalLable2 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        vatCombobox1 = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        customerIDText1 = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(1600, 1600));
        setPreferredSize(new java.awt.Dimension(1600, 1600));

        billTable.setBackground(new java.awt.Color(240, 240, 240));
        billTable.setFont(new java.awt.Font("Arial", 0, 18));
        billTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Prod ID", "Name", "Unit Price", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Float.class, java.lang.Object.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        billTable.setRowHeight(24);
        billTable.setRowMargin(5);
        billTable.setSelectionBackground(new java.awt.Color(204, 204, 255));
        billTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                billTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(billTable);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel7.setText("Item Code");

        jButton2.setFont(new java.awt.Font("Arial", 1, 14));

        userIDLabel.setFont(new java.awt.Font("Arial", 2, 14));
        userIDLabel.setText("001034");

        confirmBtn.setFont(new java.awt.Font("Arial", 1, 14));
        confirmBtn.setText("Save And Print");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        cancelBtn.setFont(new java.awt.Font("Arial", 1, 14));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel23.setText("Customer Number");

        customerIDText.setFont(new java.awt.Font("Arial", 1, 14));
        customerIDText.setText("0000000001");

        jLabel22.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel21.setText("Grand Total");

        vatCombobox.setEditable(true);
        vatCombobox.setFont(new java.awt.Font("Arial", 0, 12));
        vatCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12.3", "14.5", "4.6" }));
        vatCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vatComboboxActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel15.setText("Vat @");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel17.setText("Total");

        totalLable.setFont(new java.awt.Font("Arial", 1, 14));
        totalLable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        totalLable1.setFont(new java.awt.Font("Arial", 1, 18));
        totalLable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        totalLable2.setFont(new java.awt.Font("Arial", 1, 18));
        totalLable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel24.setText("payment Mode");

        vatCombobox1.setEditable(true);
        vatCombobox1.setFont(new java.awt.Font("Arial", 1, 14));
        vatCombobox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "cash", "card" }));
        vatCombobox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vatCombobox1ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel25.setText("Customer Name");

        customerIDText1.setFont(new java.awt.Font("Arial", 1, 14));
        customerIDText1.setText("0000000001");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customerIDText)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 778, Short.MAX_VALUE)
                        .addComponent(userIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(customerIDText1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(confirmBtn)
                                .addGap(87, 87, 87)
                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(141, 141, 141)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(vatCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(totalLable1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalLable2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                    .addComponent(totalLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(vatCombobox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(customerIDText, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel22)))
                        .addGap(43, 43, 43)))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(customerIDText1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vatCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(totalLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalLable2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalLable, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(vatCombobox1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1039, 1039, 1039))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {customerIDText, jButton2, jLabel15, jLabel17, jLabel21, jLabel22, jLabel23, jLabel25, jLabel7, totalLable, totalLable1, vatCombobox});

    }// </editor-fold>//GEN-END:initComponents

    private void billTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_billTableKeyPressed
        //     System.out.println("Key pressed..");
        // TODO add your handling code here:
}//GEN-LAST:event_billTableKeyPressed

     private void populateGridwithDetails(String barcode) throws SQLException {
       
                ItemDAO itemDao = ItemDAO.getDetails(barcode);
                String[] data = {barcode, itemDao.getPName(), "" + itemDao.getPSalePrice(), "1", "" + itemDao.getPSalePrice()};
                model.addRow(data);
                billTable.setModel(model);
                Toolkit.getDefaultToolkit().beep();
               customerIDText1.setText("");
         }

    private void populateFinalBill() {
        float total = 0;
        int count = billTable.getRowCount();
        System.out.println("Count = " + count);
        for (int i = 0; i < count; i++) {
            String str = (String) billTable.getValueAt(i, 4);
            if (str != null && !str.equals("null")) {
                total += Float.parseFloat(str);
            }
        }
        updateGrandTotal(total);
    }

     private void updateGrandTotal(float total){
        String value = ""+total;
        totalLable.setText(value);
        vatCombobox.getSelectedItem().toString();


     }

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
//         TODO add your handling code here:
//               BillingController.getInstance().
        TransactionModel trModel = new TransactionModel();
        trModel.setProdDetails(preparelisttoupdateDB(billTable.getModel()));
        String cID = customerIDText.getText();
        if(cID == null || cID.trim().equals("")){
            cID = "0000000000";
        }
        trModel.setCustomerID(cID);
//        trModel.setBillAmount(Double.parseDouble(grandTotallAmntLbl.getText()));
        trModel.setUserID(userIDLabel.getText());
//        trModel.setDiscount(Float.parseFloat(discountTxt.getText()));
        pCart = new PurchasedCart();
        TransactionManager.getInstance().addTransactionListener(pCart);
        trModel.commitPurchase();
//        Maincontroller.getInstance().launchPage(new WelcomePage());
        throw new UnknownError(); // need to implement this..
}//GEN-LAST:event_confirmBtnActionPerformed


     private void storeinHashtable(String barcode, int quantity, Hashtable<String,Integer> billedItemHashTable) {
       if(billedItemHashTable.get(barcode)!= null){
            int oldvalue = billedItemHashTable.get(barcode);
            billedItemHashTable.put(barcode, new Integer(oldvalue+quantity));
        }else{
            billedItemHashTable.put(barcode, new Integer(quantity));
        }
    }
//
    public Hashtable<String, Integer> preparelisttoupdateDB(TableModel model) {
        Hashtable<String,Integer> billedItemHashTable = new Hashtable<String, Integer>();
        int size = model.getRowCount();
        for(int i=0;i<size;i++){
            String prodID = model.getValueAt(i, 0).toString();
            int quantity = Integer.parseInt(""+model.getValueAt(i, 3));
            storeinHashtable(prodID, quantity,billedItemHashTable);
        }
        return billedItemHashTable;
   }

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        Intent intent = getIntent().getIntent(ActivityId.WELCOME_ACTIVITY);
//        intent.putExtra("com.ims.view.CONTENTPANE",(Container)getIntent().getExtra("com.ims.view.CONTENTPANE") );
        startActivity(intent);
}//GEN-LAST:event_cancelBtnActionPerformed

    private void vatComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vatComboboxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_vatComboboxActionPerformed

    private void vatCombobox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vatCombobox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vatCombobox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable billTable;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JTextField customerIDText;
    private javax.swing.JTextField customerIDText1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel totalLable;
    private javax.swing.JLabel totalLable1;
    private javax.swing.JLabel totalLable2;
    private javax.swing.JLabel userIDLabel;
    private javax.swing.JComboBox vatCombobox;
    private javax.swing.JComboBox vatCombobox1;
    // End of variables declaration//GEN-END:variables

}
