/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddProductActvity.java
 *
 * Created on Oct 6, 2015, 6:13:24 PM
 */
package com.ims.view.addproduct;

import com.ims.infra.Activity;
import com.ims.infra.Intent;
import com.ims.model.bean.ItemDAO;
import com.ims.util.Util;
import com.ims.view.ActivityId;
import java.awt.Container;

import java.awt.event.FocusEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ahbaba
 */
public class AddProductActvity extends Activity {

    @Override
    protected void onCreate() {
        super.onCreate();
        initComponents();
        hideFieldsForFood();
        super.onStart();
        Container pane = (Container) getIntent().getExtra("com.ims.view.CONTENTPANE");
        pane.add(this);
        pane.revalidate();
    }

    /** Creates new form AddProductActvity */
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prodBarCodeText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        prodDescription = new javax.swing.JTextField();
        prodTypeText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        prodNameText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        prodQuantityText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        prodSalePriceText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        prodPurchasePriceText = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        prodSupplier = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        prodBarCodeText.setFont(new java.awt.Font("Arial", 1, 18));
        prodBarCodeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodBarCodeTextActionPerformed(evt);
            }
        });
        prodBarCodeText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prodBarCodeTextKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel8.setText("Quantity");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        prodDescription.setFont(new java.awt.Font("Arial", 1, 18));
        prodDescription.setName(""); // NOI18N
        prodDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodDescriptionActionPerformed(evt);
            }
        });

        prodTypeText.setFont(new java.awt.Font("Arial", 1, 18));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel10.setText("Description");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        prodNameText.setFont(new java.awt.Font("Arial", 1, 18));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel5.setText("Type");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        prodQuantityText.setFont(new java.awt.Font("Arial", 1, 18));
        prodQuantityText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                prodQuantityTextFocusLost(evt);
            }
        });
        prodQuantityText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prodQuantityTextKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel7.setText("Sale price");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        prodSalePriceText.setFont(new java.awt.Font("Arial", 1, 18));
        prodSalePriceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodSalePriceTextActionPerformed(evt);
            }
        });
        prodSalePriceText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                prodSalePriceTextFocusLost(evt);
            }
        });
        prodSalePriceText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prodSalePriceTextKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel3.setText("Item code");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        addButton.setFont(new java.awt.Font("Arial", 1, 24));
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel4.setText("Name");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton2.setFont(new java.awt.Font("Arial", 1, 24));
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel9.setText("Purchase price");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel2.setText("Expiry Date");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        prodPurchasePriceText.setFont(new java.awt.Font("Arial", 1, 18));
        prodPurchasePriceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodPurchasePriceTextActionPerformed(evt);
            }
        });
        prodPurchasePriceText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                prodPurchasePriceTextFocusLost(evt);
            }
        });
        prodPurchasePriceText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prodPurchasePriceTextKeyTyped(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Arial", 1, 12));
        updateButton.setText("+");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Arial", 1, 24));
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel11.setText("Supplier Name");
        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        prodSupplier.setFont(new java.awt.Font("Arial", 1, 18));
        prodSupplier.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                prodSupplierFocusLost(evt);
            }
        });
        prodSupplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prodSupplierKeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 1, 12));
        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prodSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                            .addComponent(jXDatePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                            .addComponent(prodNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                            .addComponent(prodTypeText, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                            .addComponent(prodSalePriceText, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                            .addComponent(prodPurchasePriceText, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                            .addComponent(prodQuantityText, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                            .addComponent(prodDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                            .addComponent(prodBarCodeText, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(403, 403, 403))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(prodBarCodeText, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                        .addComponent(updateButton))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodSalePriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodPurchasePriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodQuantityText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(prodSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void prodBarCodeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodBarCodeTextActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_prodBarCodeTextActionPerformed

     private void hideFieldsForFood() {
       int prodType = Integer.parseInt(getIntent().getExtra("com.ims.view.welcome.ITEM").toString());
       if(prodType == ProdType.FOOD){
           prodPurchasePriceText.setVisible(false);
           jLabel9.setVisible(false);
           prodQuantityText.setVisible(false);
           jLabel8.setVisible(false);
           jXDatePicker1.setVisible(false);
           jLabel2.setVisible(false);
           prodDescription.setVisible(false);
           jLabel10.setVisible(false);
       }
    }


    private void prodBarCodeTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prodBarCodeTextKeyTyped
        // TODO add your handling code here:
        if (!Util.isNumberKeys(evt.getKeyChar())) {
            evt.consume();
        }
}//GEN-LAST:event_prodBarCodeTextKeyTyped

    private void prodDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodDescriptionActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_prodDescriptionActionPerformed

    private void prodQuantityTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prodQuantityTextFocusLost
        // TODO add your handling code here:
        validateNumber(evt);
}//GEN-LAST:event_prodQuantityTextFocusLost

    private void prodQuantityTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prodQuantityTextKeyTyped
        // TODO add your handling code here:
        if (!Util.isNumberKeys(evt.getKeyChar())) {
            evt.consume();
        }
}//GEN-LAST:event_prodQuantityTextKeyTyped

    protected void onDestroy() {
        super.onDestroy();
        ((Container) getIntent().getExtra("com.ims.view.CONTENTPANE")).remove(this);
        setVisible(false);
    }

    private void prodSalePriceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodSalePriceTextActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_prodSalePriceTextActionPerformed

    private void prodSalePriceTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prodSalePriceTextFocusLost
        // TODO add your handling code here:
        validateNumber(evt);
}//GEN-LAST:event_prodSalePriceTextFocusLost

    private void validateNumber(FocusEvent evt) {
        if (!Util.validateNumberPresent((JTextField) (evt.getSource()))) {
            ((JTextField) evt.getSource()).requestFocus();
            JOptionPane.showMessageDialog(null, "Please enter proper value", "" + "Confirmation", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void prodSalePriceTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prodSalePriceTextKeyTyped
        // TODO add your handling code here:
        if (!Util.isFloatingPointNumber(evt.getKeyChar())) {
            evt.consume();
        }
}//GEN-LAST:event_prodSalePriceTextKeyTyped

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        gatherDataFromUI();
}//GEN-LAST:event_addButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        clearItem();
}//GEN-LAST:event_jButton2ActionPerformed

    private void prodPurchasePriceTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prodPurchasePriceTextFocusLost
        // TODO add your handling code here:
        validateNumber(evt);
}//GEN-LAST:event_prodPurchasePriceTextFocusLost

    private void prodPurchasePriceTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prodPurchasePriceTextKeyTyped
        // TODO add your handling code here:
        if (!Util.isFloatingPointNumber(evt.getKeyChar())) {
            evt.consume();
        }
}//GEN-LAST:event_prodPurchasePriceTextKeyTyped

    private void gatherDataFromUI() {

        ItemDAO item = new ItemDAO();
        item.setPID(prodBarCodeText.getText());
        item.setPName(prodNameText.getText());
        item.setPType(prodTypeText.getText());
        item.setPSalePrice(Float.parseFloat(prodSalePriceText.getText()));
        item.setPPurchasePrice(Float.parseFloat(prodPurchasePriceText.getText()));
        item.setPQuantity(Integer.parseInt(prodQuantityText.getText()));
        item.setPDescription(prodDescription.getText());
        item.setPExpityDate(jXDatePicker1.getDate());
//        item.saveProduct(item);
        clearItem();
        JOptionPane.showMessageDialog(null, "Item Added Successfully", "" + "Confirmation", JOptionPane.INFORMATION_MESSAGE);
    }
//        createServerRequest(item);

    private void clearItem() {
        jXDatePicker1.setDate(null);
        prodBarCodeText.setText("");
        prodNameText.setText("");
        prodPurchasePriceText.setText("");
        prodQuantityText.setText("");
        prodSalePriceText.setText("");
        prodTypeText.setText("");
        prodDescription.setText("");
        prodBarCodeText.requestFocus();
    }
    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        gatherDataFromUI();
}//GEN-LAST:event_updateButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Intent intent = getIntent().getIntent(ActivityId.WELCOME_ACTIVITY);
        startActivity(intent);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void prodPurchasePriceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodPurchasePriceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodPurchasePriceTextActionPerformed

    private void prodSupplierFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prodSupplierFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_prodSupplierFocusLost

    private void prodSupplierKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prodSupplierKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_prodSupplierKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      Intent intent = getIntent().getIntent(ActivityId.ADD_SUPPLIER_ACTIVITY);
        startActivity(intent);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void populateItemDetails(ItemDAO item) {
        prodNameText.setText(item.getPName());
        prodTypeText.setText(item.getPType());
        prodSalePriceText.setText("" + item.getPSalePrice());
        prodPurchasePriceText.setText("" + item.getPPurchasePrice());
        prodQuantityText.setText("" + item.getPQuantity());
//       jXDatePicker1.setDate(new Date(item.getPExpityDate()));
        prodDescription.setText(item.getPDescription());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JTextField prodBarCodeText;
    private javax.swing.JTextField prodDescription;
    private javax.swing.JTextField prodNameText;
    private javax.swing.JTextField prodPurchasePriceText;
    private javax.swing.JTextField prodQuantityText;
    private javax.swing.JTextField prodSalePriceText;
    private javax.swing.JTextField prodSupplier;
    private javax.swing.JTextField prodTypeText;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables


}
