//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.22 at 10:54:31 AM IST 
//


package com.jeet.pos;

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="offerid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="offerDetail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="discount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "offerid",
    "offerDetail",
    "discount",
    "itemOffer"
})
@XmlRootElement(name = "offer")
public class Offer {

	@XmlElement(required = true)
    protected int offerid;
    @XmlElement(required = true)
    protected String offerDetail;
    @XmlElement(required = true)
    protected int discount;
    
    @XmlElement(required = true)
    protected Set<ItemOffer> itemOffer = new HashSet<ItemOffer>();

    /**
     * Gets the value of the offerid property.
     * 
     */
    public int getOfferid() {
        return offerid;
    }

    /**
     * Sets the value of the offerid property.
     * 
     */
    public void setOfferid(int value) {
        this.offerid = value;
    }

    /**
     * Gets the value of the offerDetail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferDetail() {
        return offerDetail;
    }

    /**
     * Sets the value of the offerDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferDetail(String value) {
        this.offerDetail = value;
    }

    /**
     * Gets the value of the discount property.
     * 
     */
    public int getDiscount() {
        return discount;
    }

    /**
     * Sets the value of the discount property.
     * 
     */
    public void setDiscount(int value) {
        this.discount = value;
    }

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Item }
     * 
     * 
     */
   /* public Set<ItemOffer> getItemOffer() {
        return this.itemOffer;
    }*/

}
